# Generated by Django 5.0.6 on 2024-06-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_delete_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='estimated_cost',
            field=models.TextField(),
        ),
    ]
